version: '2'
mem_reservation: 720m
services:
  jsonapi-schema-generator:
   image: 816461209558.dkr.ecr.eu-central-1.amazonaws.com/jsonapi-schema-generator
   build: .
   command: bash -c "bundle exec rake db:migrate && bundle exec puma -C config/puma.rb"
      
#  volumes:
#    - ./log:/jsonapi-schema-generator/log
#    - ./config:/jsonapi-schema-generator/config
   ports:
     - '80:3000'
   env_file:
     - .jsonapi-schema-generator.env
   logging:
     driver: awslogs
     options:
       awslogs-region: eu-central-1
       awslogs-group: jsonapi-schema-generator
